### ISSUE TITLE
Implementation of section "Combating excessive regularization"

### ISSUE THREAD

**Issue by hbredin** [uoguelph-mlrg/confidence_estimation#2]
In section 2.3.2 of the paper, it says:

```
We find that giving hints with 50% probability addresses this
issue, as the gradients from low confidence examples now
have a chance of backpropagating unhindered and updating
the decision boundary, but we still learn useful confidence
estimates. One way we can implement this in practice is
by applying Equation 2 to only half of the batch at each
iteration.
```

If I am not mistaken, the following lines are where this idea is implemented:

https://github.com/uoguelph-mlrg/confidence_estimation/blob/c98f23d0c5e44b4310c14d6986e298ec81ecfcdc/train.py#L242-L244

Does this really `set half of the confidences to 1`? 
Is applying `bernoulli` on uniform samples between `[0, 1]` really equivalent?
Would applying a threshold at 0.5 on each uniform sample work as well?

**Comment by TDeVries** [comment]
Thresholding at 0.5 on each uniform sample would also probably work fine.
