### ISSUE TITLE
Where is the implementation of input preprecessing presented  at section 3.1 of the paper

### ISSUE THREAD

**Issue by suruoxi** [uoguelph-mlrg/confidence_estimation#3]
In the paper, there's input preprocessing:

![](https://i.imgur.com/xcKZJYI.png)

**Comment by TDeVries** [comment]
I called input preprocessing "confidence scaling" in the code for some reason: https://github.com/uoguelph-mlrg/confidence_estimation/blob/c98f23d0c5e44b4310c14d6986e298ec81ecfcdc/out_of_distribution_detection.py#L199
